[package]
name = "verify_cli"
version = "0.1.0"
edition = "2021"

[dependencies]
boojum = {path = "../boojum"}
zkevm_circuits = {path = "../zkevm_circuits"}
zkevm_test_harness = {path = "../zkevm_test_harness"}
circuit_definitions = {path = "../zkevm_test_harness/circuit_definitions"}
bincode = "*"
colored = "2.0"
serde_json = "*"